### ISSUE TITLE
Tests failing on 'no config vars for <app>'

### ISSUE THREAD

**Issue by byrnedo** [dokku/dokku-nats#1]
@josegonzalez, sorry to bother you, but wondering is there a simple reason why I'm getting 'no config vars for <x>' in the tests? 
If you've a quick answer then great, otherwise I'll roll my sleeves up :)

**Comment by josegonzalez** [comment]
Nope, @Flink ?

**Comment by Flink** [comment]
It reminds me something but I’m not sure and I don’t think it gave an error.

**Comment by byrnedo** [comment]
I had copy/pasta'd the tests from the redis project and went through changing urls/ports etc. And then this cropped up. I must have missed something just.

**Comment by SharpEdgeMarshall** [comment]
There are news about why tests are failing?

**Comment by byrnedo** [comment]
Yeah, its something I've been meaning to fix. The project is based on
dokku-redis, it must be something that I didn't change correctly when I
created this repo.

**Comment by SharpEdgeMarshall** [comment]
i added vagrantfile and updated plugn just for that reason.
I was hoping that would solve the issue but no luck.

I'll do a diff and try to find the differences

**Comment by byrnedo** [comment]
Thanks Fabio.

**Comment by SharpEdgeMarshall** [comment]
It seems impossible to find this bug! The repos are almost the same!

**Comment by josegonzalez** [comment]
@byrnedo I "fixed" the tests so that they at least run.

**Comment by byrnedo** [comment]
Thanks Jose.

**Comment by josegonzalez** [comment]
I fixed all the tests :)

**Comment by byrnedo** [comment]
You're the man :)
