### ISSUE TITLE
More config possibilities

### ISSUE THREAD

**Issue by byrnedo** [dokku/dokku-nats#2]
Need a better way to set all config options. 
May create pull request on main nats config code if it's simple.
Right now there's no env support, but it's on the roadmap so no point in making a workaround right now.

**Comment by josegonzalez** [comment]
This should be possible if we change up how we reference the options and pull the nats.conf from the repo.

https://github.com/nats-io/nats-docker/pull/4

**Comment by josegonzalez** [comment]
This is unlikely to be worked on, so closing the issue out since its stale.
