### ISSUE TITLE
Can't enter service container

### ISSUE THREAD

**Issue by vomba** [dokku/dokku-nats#49]
## Description of problem
As the title says, you can't enter a running service container
### How reproducible
dokku nats:enter <service-name>
 
### Result

OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: exec: "/bin/bash": stat /bin/bash: no such file or directory: unknown

**Comment by josegonzalez** [comment]
For now, the workaround is maybe:

```
dokku nats:enter sh
```
